# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: htt

on:
  workflow_dispatch:
  schedule:
     - cron: '*/5 0-16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        htt_videoname: ${{ secrets.htt_videoname }}
        htt_dongfangname: ${{ secrets.htt_dongfangname }}
        htt_smvideoname: ${{ secrets.htt_smvideoname }}
        htt_signurlckname: ${{ secrets.htt_signurlckname }}
        htt_signbdname: ${{ secrets.htt_signbdname }}
        
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/hahahrfool/htt.git ~/htt
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          cd ~/htt
          npm install
          
      - name: '运行 '
        run: |
          cd ~/htt
          node Scripts/HTT/htt_ac.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}

    
